# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterClient' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'BDBOAuth1Manager'
  pod 'AFNetworking', '3.0.0'  
# Pods for TwitterClient, '2.0.0'

end
